FROM mcr.microsoft.com/dotnet/core/runtime:3.0.0-preview7-buster-slim-arm64v8 AS base 
RUN apk add --no-cache --update 'mariadb-client>10.3.17'
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview7-buster-arm64v8 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "ddb.csproj" -r linux-arm -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=build /app .
RUN mkdir /app/backup
VOLUME ["/app/backup"]
ENTRYPOINT ["./ddb"]