version: "3.7"
services:
  ddb:
    image: ddb:beta
    environment:
      MYSQL_ADRESS: "database.platnicyvat.pl"
      MYSQL_PORT: "3445"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "jrmgqj2xf1e24tgx"
      DB_DUMP_FREQ: "3"
      DB_DUMP_BEGIN: "2000"
    volumes:
      - "D:/VB_Shared:/app/backup"
    restart: on-failure

