version: "3.7"
services:
  ddb:
    image: ddb:beta
    environment:
      MYSQL_ADRESS: 
      MYSQL_PORT: "3445"
      MYSQL_USERNAME: 
      MYSQL_PASSWORD: 
      DB_DUMP_FREQ: "60"
      DB_DUMP_BEGIN: "1105"
    volumes:
      - "D:/VB_Shared:/app/backup"
    restart: on-failure

